<?php 
  return [
    'generic_names' => [
      'Ceftriaxone',
      'Cefazolin',
      'Ceftazidime',
      'Ceftrialisis',
      'Dexamethasone',
      'Furosemide',
      'Ketoprofen',
      'Losartan',
      'Neotalis',
      'Ranitidine',
      'Pantoprazole',
      'Sodium Bicarbonate',
      'Vitamin A',
      'Betamethasone',
      'Metronidazole',
      'Multivitamins',
      'Vitamin K',
      'Ampicillin',
      'Diphenhydramine',
      'Gentamicin',
      'Vitamin B Complex',
      'Omeprazole',
      'Cephalexin',
      'Clindamycin',
    ],
    'brand_names' => [
      'Arcimet',
      'Cefazovit',
      'Ceftazivit',
      'No Brand Name',
      'Dexavit',
      'Furotalis',
      'Ketonix',
      'Losil',
      'No Brand Name',
      'Ranicid',
      'Pantrex',
      'Sodicarb',
      'Vitaroxima',
      'Vitasone',
      'Vitazol',
      'Vitral',
      'Ambivit K',
      'Amiphil',
      'Diphenpors',
      'Gentacare',
      'Neurobe',
      'Oprex',
      'Sapharin',
      'Tidact',
    ],
  ];
?>
