<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Print Order #{{ $order->id }}</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            font-size: 12pt;
            color: #000;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            text-transform: uppercase;
            font-size: 18pt;
        }
        .header p {
            margin: 2px 0;
        }
        .meta-info {
            width: 100%;
            margin-bottom: 20px;
        }
        .meta-info td {
            vertical-align: top;
            padding: 5px;
        }
        .label {
            font-weight: bold;
            width: 120px;
            display: inline-block;
        }
        table.items {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        table.items th, table.items td {
            border: 1px solid #000;
            padding: 8px;
            text-align: left;
        }
        table.items th {
            background-color: #f0f0f0;
            text-transform: uppercase;
            font-size: 10pt;
        }
        .signatures {
            margin-top: 50px;
            display: flex;
            justify-content: space-between;
        }
        .sig-box {
            width: 30%;
            text-align: center;
        }
        .line {
            border-top: 1px solid #000;
            margin-top: 40px;
            margin-bottom: 5px;
        }
        @media print {
            .no-print {
                display: none;
            }
            body {
                padding: 0;
            }
        }
    </style>
</head>
<body>

    {{-- Print Button (Hidden when printing) --}}
    <div class="no-print" style="margin-bottom: 20px; text-align: right;">
        <button onclick="window.print()" style="padding: 10px 20px; cursor: pointer; background: #333; color: #fff; border: none; border-radius: 5px;">
            Print / Save as PDF
        </button>
    </div>

    {{-- Document Header --}}
    <div class="header">
        <h1>Medicine Replenishment Order</h1>
        <p>Generated by RCT MED PHARMA System</p>
        <p>Date Generated: {{ date('F d, Y') }}</p>
    </div>

    {{-- Order Meta Data --}}
    <table class="meta-info">
        <tr>
            <td width="50%">
                <div><span class="label">Order ID:</span> #{{ $order->id }}</div>
                <div><span class="label">Date Created:</span> {{ $order->created_at->format('M d, Y h:i A') }}</div>
                <div><span class="label">Status:</span> {{ strtoupper($order->status) }}</div>
            </td>
            <td width="50%">
                <div><span class="label">Requesting Branch:</span> {{ $order->branch->name }}</div>
                <div><span class="label">Requested By:</span> {{ $order->user->name }}</div>
            </td>
        </tr>
    </table>

    {{-- Items Table --}}
    <table class="items">
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 45%;">Generic Name</th>
                <th style="width: 35%;">Brand Name</th>
                <th style="width: 15%; text-align: center;">Qty Requested</th>
            </tr>
        </thead>
        <tbody>
            @foreach($order->items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item->product->generic_name }}</td>
                <td>{{ $item->product->brand_name }}</td>
                <td style="text-align: center; font-weight: bold;">{{ number_format($item->quantity_requested) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{-- Remarks --}}
    @if($order->remarks)
    <div style="margin-bottom: 30px; border: 1px dashed #000; padding: 10px;">
        <strong>Notes/Remarks:</strong> <br>
        {{ $order->remarks }}
    </div>
    @endif

    {{-- Approval Signatures --}}
    <div class="signatures">
        <div class="sig-box">
            <div class="line"></div>
            <strong>Prepared By</strong><br>
            <span>{{ $order->user->name }}</span><br>
            <small>Pharmacist / Requester</small>
        </div>

        <div class="sig-box">
            <div class="line"></div>
            <strong>Admin Approved</strong><br>
            <span>Date: {{ $order->admin_approved_at ? \Carbon\Carbon::parse($order->admin_approved_at)->format('M d, Y') : 'N/A' }}</span>
        </div>

        <div class="sig-box">
            <div class="line"></div>
            <strong>Finance Approved</strong><br>
            <span>Date: {{ $order->finance_approved_at ? \Carbon\Carbon::parse($order->finance_approved_at)->format('M d, Y') : 'N/A' }}</span>
        </div>
    </div>

    <script>
        // Optional: Automatically trigger print when page loads
        // window.onload = function() { window.print(); }
    </script>
</body>
</html>