<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;
use Exception;
use Illuminate\Support\Facades\Log;

class ExportController extends Controller
{
    /**
     * Enhanced text sanitization for XML compatibility
     */
    private function sanitizeForXml($input)
    {
        if ($input === null) {
            return '';
        }
        
        // Convert to string
        $text = (string) $input;
        
        // Remove any invalid UTF-8 characters
        $text = mb_convert_encoding($text, 'UTF-8', 'UTF-8');
        
        // Remove control characters (except tab, line feed, and carriage return)
        $text = preg_replace(
            '/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/',
            '',
            $text
        );
        
        // Remove any characters not allowed in XML
        $text = preg_replace(
            '/[^\x{0009}\x{000A}\x{000D}\x{0020}-\x{D7FF}\x{E000}-\x{FFFD}\x{10000}-\x{10FFFF}]/u',
            '',
            $text
        );
        
        // Escape XML special characters
        $text = htmlspecialchars($text, ENT_XML1 | ENT_QUOTES, 'UTF-8');
        
        return $text;
    }

    /**
     * Create a safe text run for PhpWord
     */
    private function addSafeText($element, $text, $fontStyle = null, $paragraphStyle = null)
    {
        $text = $this->sanitizeForXml($text);
        $element->addText($text, $fontStyle, $paragraphStyle);
    }

    public function exportDocx(Request $request)
    {
        // Increase resources for large documents
        set_time_limit(300);
        ini_set('memory_limit', '512M');
        ini_set('default_charset', 'UTF-8');
        
        ob_start();

        try {
            $validated = $request->validate([
                'products' => 'required|array|min:1'
            ]);
            $products = $validated['products'];

            $phpWord = new PhpWord();
            
            // Set document properties
            $phpWord->getDocInfo()
                ->setCreator('RMPOIMS')
                ->setCompany('RMPOIMS')
                ->setTitle('Inventory Export')
                ->setDescription('Inventory export generated by RMPOIMS');
            
            // Set default font
            $phpWord->setDefaultFontName('Arial');
            $phpWord->setDefaultFontSize(10);
            
            $section = $phpWord->addSection();

            // --- Header and Title ---
            $this->addSafeText(
                $section,
                'RMPOIMS - OCR Scanned Copy of Acknowledgement Receipt',
                ['bold' => true, 'size' => 16],
                ['alignment' => \PhpOffice\PhpWord\SimpleType\Jc::CENTER]
            );
            
            $this->addSafeText(
                $section,
                'Generated on: ' . date('F j, Y, g:i a'),
                ['size' => 10],
                ['alignment' => \PhpOffice\PhpWord\SimpleType\Jc::CENTER]
            );
            
            $section->addTextBreak(1);

            // --- Main Products Table ---
            $tableStyle = [
                'borderSize' => 6, 
                'borderColor' => '999999', 
                'cellMargin' => 80,
                'alignment' => \PhpOffice\PhpWord\SimpleType\Jc::CENTER
            ];
            
            $headerStyle = ['bold' => true, 'bgColor' => 'EEEEEE'];
            $phpWord->addTableStyle('InventoryTable', $tableStyle, $headerStyle);
            $table = $section->addTable('InventoryTable');
            
            // Table Header - Updated to have combined product name column
            $table->addRow();
            $this->addSafeText($table->addCell(500), '#', $headerStyle);
            $this->addSafeText($table->addCell(3500), 'Product Name (Generic Name & Brand Name)', $headerStyle);
            $this->addSafeText($table->addCell(1000), 'Strength', $headerStyle);
            $this->addSafeText($table->addCell(1000), 'Form', $headerStyle);
            $this->addSafeText($table->addCell(800), 'Qty', $headerStyle);
            $this->addSafeText($table->addCell(1500), 'Batch No.', $headerStyle);
            $this->addSafeText($table->addCell(1500), 'Expiry', $headerStyle);
            $this->addSafeText($table->addCell(1500), 'Location', $headerStyle);

            // Table Body - Combine generic name and brand name
            foreach ($products as $index => $product) {
                $table->addRow();
                $this->addSafeText($table->addCell(500), (string)($index + 1));
                
                // Combine generic name and brand name
                $genericName = $product['generic_name'] ?? ($product['product_name'] ?? '');
                $brandName = $product['brand_name'] ?? '';
                
                // Create the combined product name
                if (!empty($genericName) && !empty($brandName)) {
                    $combinedName = $genericName . ' - ' . $brandName;
                } elseif (!empty($genericName)) {
                    $combinedName = $genericName;
                } elseif (!empty($brandName)) {
                    $combinedName = $brandName;
                } else {
                    $combinedName = 'N/A';
                }
                
                $this->addSafeText($table->addCell(3500), $combinedName);
                $this->addSafeText($table->addCell(1000), $product['strength'] ?? 'N/A');
                $this->addSafeText($table->addCell(1000), $product['form'] ?? 'N/A');
                $this->addSafeText($table->addCell(800), $product['quantity'] ?? 'N/A');
                $this->addSafeText($table->addCell(1500), $product['batch_number'] ?? 'N/A');
                $this->addSafeText($table->addCell(1500), $product['expiry_date'] ?? 'N/A');
                $this->addSafeText($table->addCell(1500), $product['location'] ?? 'N/A');
            }
            
            // --- Footer Section ---
            $section->addTextBreak(2);
            
            $footerTableStyle = ['borderSize' => 0, 'borderColor' => 'ffffff', 'cellMargin' => 0];
            $phpWord->addTableStyle('footerTableStyle', $footerTableStyle);
            $footerTable = $section->addTable('footerTableStyle');
            $footerTable->addRow();
            
            // Left side of footer
            $leftCell = $footerTable->addCell(5500);
            $this->addSafeText($leftCell, 'Remarks:', ['bold' => true]);
            $this->addSafeText($leftCell, '___________________________________');
            $this->addSafeText($leftCell, '___________________________________');
            $this->addSafeText($leftCell, '___________________________________');
            $leftCell->addTextBreak(2);
            $this->addSafeText($leftCell, 'Received By: _________________________');
            $this->addSafeText($leftCell, '                                      Print Name & Signature', ['size' => 8]);
            
            // Right side of footer
            $rightCell = $footerTable->addCell(5500);
            $this->addSafeText($rightCell, 'Prepared By:       ____________________');
            $this->addSafeText($rightCell, 'Checked By:         ____________________');
            $this->addSafeText($rightCell, 'Double Checked By: ____________________');
            $rightCell->addTextBreak(1);
            $this->addSafeText($rightCell, 'Released By:       ____________________');
            $this->addSafeText($rightCell, 'Date Released:    ____________________');
            $rightCell->addTextBreak(1);
            
            $dateTable = $rightCell->addTable('footerTableStyle');
            $dateTable->addRow();
            $dateCell = $dateTable->addCell();
            $this->addSafeText($dateCell, 'Date: ______________________________');

            // --- File Saving and Downloading ---
            $objWriter = IOFactory::createWriter($phpWord, 'Word2007');
            
            // Generate a safe filename
            $fileName = 'RMPOIMS_Inventory_' . date('Y-m-d_His') . '.docx';
            $tempFile = sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid('PHPWord_') . '_' . $fileName;
            
            // Save the document
            $objWriter->save($tempFile);
            
            // Verify the file was created successfully
            if (!file_exists($tempFile)) {
                throw new Exception('Failed to create the document file.');
            }
            
            // Save to storage if needed
            $datePath = Carbon::now()->format('Y/m/d');
            $fullPath = 'receipts/docs_ocr_copy/' . $datePath . '/' . $fileName;
            Storage::disk('public')->put($fullPath, file_get_contents($tempFile));

            ob_end_clean();

            // Download the file with proper headers
            return response()->download(
                $tempFile, 
                $fileName,
                [
                    'Content-Type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'Content-Disposition' => 'attachment; filename="' . $fileName . '"'
                ]
            )->deleteFileAfterSend(true);

        } catch (Exception $e) {
            ob_end_clean();
            Log::error('DOCX Export Failed: ' . $e->getMessage());
            Log::error('Trace: ' . $e->getTraceAsString());
            
            return response()->json([
                'error' => 'Could not generate the document due to a server error.',
                'message' => $e->getMessage()
            ], 500);
        }
    }
}